# Codebook

## Variables

subject - Subject (1-30)

activity - Six different activities

In the remaining variable names, the following variable are included in terms of their means and standard deviations:

* BodyAcc - Body acceleration signal in standard gravity units (g)

* GravityAcc - Gravity acceleration signal in standard gravity units (g)

* BodyAccJerk - Body acceleration jerk in standard gravity units (g)

* BodyGyro- from gyroscore

* BodyGyroJerk-  body linear acceleration and angular velocity

* BodyAccMag - body linear acceleration and angular velocity

* GravityAccMag - body linear acceleration and angular velocity

* BodyAccJerkMag - body linear acceleration and angular velocity

* BodyGyroMag - body linear acceleration and angular velocity

* BodyGyroJerkMag - body linear acceleration and angular velocity

* BodyAcc- Body acceleration signal in standard gravity units (g)

* BodyAccJerk - Body acceleration jerk in standard gravity units (g)

* BodyGyro -  from gyroscore

* BodyAccMag -  body linear acceleration and angular velocity

* BodyBodyAccJerkMag -  body linear acceleration and angular velocity

* BodyBodyGyroMag -  body linear acceleration and angular velocity

* BodyBodyGyroJerkMag -  body linear acceleration and angular velocity
